version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: travel-blog-admin
    container_name: travel-blog-admin-app
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www
    depends_on:
      - mysql

  mysql:
    image: mysql:8.0
    container_name: travel-blog-admin-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
